/*
 * \"Explore With Me\" API сервер
 * Documentation \"Explore With Me\" API v1.0
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.mainservice.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class CommentDto {
    private UserShortDto user;
    private LocalDateTime createdOn;
    private LocalDateTime updateOn;
    private String text;
}
